"""
modules/week10_kit.py
Week 10: Integration & Streamlit Cloud Deployment — Full Brand Kit
"""
import streamlit as st
import json, zipfile, io, os, datetime
import matplotlib.pyplot as plt
import matplotlib; matplotlib.use("Agg")
from utils.session import mark_done


def _safe_pick(lst, idx):
    """Safely get item from list — returns None instead of raising IndexError."""
    if not lst:
        return None
    if idx is None:
        return lst[0] if lst else None
    try:
        return lst[int(idx)]
    except (IndexError, TypeError, ValueError):
        return lst[0] if lst else None


def _build_kit_zip() -> bytes:
    company  = st.session_state.get("company", "Brand")
    slogans  = st.session_state.get("slogans") or []
    fonts    = st.session_state.get("fonts") or []
    palettes = st.session_state.get("palettes") or []
    campaign = st.session_state.get("campaign") or {}
    translations = st.session_state.get("translations") or []

    sel_sl  = st.session_state.get("selected_slogan")
    sel_fnt = st.session_state.get("selected_font")
    sel_pal = st.session_state.get("selected_palette")

    slogan_obj  = _safe_pick(slogans, sel_sl)
    font_obj    = _safe_pick(fonts, sel_fnt)
    palette_obj = _safe_pick(palettes, sel_pal)
    slogan_text = slogan_obj["text"] if isinstance(slogan_obj, dict) else ""

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:

        # ── brand_manifest.json ───────────────────────────────────────────────
        manifest = {
            "meta": {
                "company":   company,
                "industry":  st.session_state.get("industry", ""),
                "tone":      st.session_state.get("tone", ""),
                "audience":  st.session_state.get("audience", ""),
                "generated": datetime.datetime.now().isoformat(),
            },
            "logo":             {"selected_variant": st.session_state.get("selected_logo")},
            "typography":       font_obj,
            "slogans":          slogans,
            "selected_slogan":  slogan_obj,
            "color_palettes":   palettes,
            "selected_palette": palette_obj,
            "campaign":         campaign,
            "translations":     translations,
            "feedback":         st.session_state.get("feedback"),
        }
        zf.writestr("brand_manifest.json",
                    json.dumps(manifest, indent=2, ensure_ascii=False))

        # ── campaign_copy.txt ─────────────────────────────────────────────────
        lines = [
            f"BRAND KIT — {company.upper()}",
            "=" * 50,
            f"Industry: {st.session_state.get('industry','')}",
            f"Tone:     {st.session_state.get('tone','')}",
            f"Audience: {st.session_state.get('audience','')}",
            "",
            "SELECTED TAGLINE",
            f'  "{slogan_text}"',
            "",
            "CAMPAIGN COPY",
            f"  Caption:   {campaign.get('caption','')}",
            f"  Format:    {campaign.get('type','')}",
            f"  Best Time: {campaign.get('bestTime','')}",
            f"  Hashtags:  {' '.join(campaign.get('hashtags',[]))}",
            "",
            "PREDICTED METRICS",
            f"  CTR:        {campaign.get('ctr','')}",
            f"  ROI:        {campaign.get('roi','')}",
            f"  Engagement: {campaign.get('engagement','')}",
        ]
        zf.writestr("campaign_copy.txt", "\n".join(lines))

        # ── colour_palette.csv ────────────────────────────────────────────────
        if palette_obj and isinstance(palette_obj, dict):
            roles = ["Primary", "Secondary", "Background", "Neutral"]
            csv_lines = ["role,hex"]
            for r, c in zip(roles, palette_obj.get("colors", [])):
                csv_lines.append(f"{r},{c}")
            zf.writestr("colour_palette.csv", "\n".join(csv_lines))

        # ── multilingual_slogans.txt ──────────────────────────────────────────
        if translations:
            t_lines = [f"MULTILINGUAL SLOGANS — {company.upper()}", "=" * 50,
                       f'English: "{slogan_text}"', ""]
            for t in translations:
                t_lines.append(f"{t.get('flag','')} {t.get('lang','')}: \"{t.get('slogan', t.get('text',''))}\"")
            zf.writestr("multilingual_slogans.txt", "\n".join(t_lines))

        # ── README.md ─────────────────────────────────────────────────────────
        readme = f"""# {company} Brand Kit
Generated by BrandMind AI — CRS AI Capstone 2025-26

## Contents
- brand_manifest.json      — Complete brand data
- campaign_copy.txt        — Captions, hashtags, metrics
- colour_palette.csv       — HEX colour codes
- multilingual_slogans.txt — Translated taglines
- README.md                — This file

Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
        zf.writestr("README.md", readme)

    buf.seek(0)
    return buf.read()


def render_kit():

    company  = st.session_state.get("company", "Your Brand")
    slogans  = st.session_state.get("slogans") or []
    fonts    = st.session_state.get("fonts") or []
    palettes = st.session_state.get("palettes") or []
    campaign = st.session_state.get("campaign") or {}

    sel_sl  = st.session_state.get("selected_slogan")
    sel_fnt = st.session_state.get("selected_font")
    sel_pal = st.session_state.get("selected_palette")

    slogan_obj  = _safe_pick(slogans, sel_sl)
    font_obj    = _safe_pick(fonts, sel_fnt)
    palette_obj = _safe_pick(palettes, sel_pal)
    slogan_text = slogan_obj["text"] if isinstance(slogan_obj, dict) else "—"

    # ── Hero ──────────────────────────────────────────────────────────────────
    st.markdown(f"""
<div style="background:#1a1a18;color:#f5f0e8;border-radius:14px;padding:28px 24px;
            text-align:center;margin-bottom:20px">
  <div style="font-size:2rem;margin-bottom:10px">✦</div>
  <h2 style="font-family:Georgia,serif;font-size:1.7rem;margin-bottom:6px">{company} Brand Kit</h2>
  <p style="opacity:0.6;font-size:0.88rem;margin-bottom:0">
    Complete AI-generated brand identity — ready for deployment
  </p>
</div>""", unsafe_allow_html=True)

    # ── Download ──────────────────────────────────────────────────────────────
    kit_zip = _build_kit_zip()
    st.download_button(
        label="⬇ Download Full Brand Kit (.zip)",
        data=kit_zip,
        file_name=f"{company.replace(' ','_')}_BrandKit.zip",
        mime="application/zip",
        use_container_width=True,
    )
    st.divider()

    # ── Brand Summary ─────────────────────────────────────────────────────────
    st.subheader("Brand Summary")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(f"**Company:** {company}")
        st.markdown(f"**Industry:** {st.session_state.get('industry','—')}")
    with c2:
        st.markdown(f"**Tone:** {st.session_state.get('tone','—')}")
        heading = font_obj.get("heading","—") if isinstance(font_obj, dict) else "—"
        st.markdown(f"**Typography:** {heading}")
    with c3:
        st.markdown(f"**Audience:** {st.session_state.get('audience','—') or '—'}")
        st.markdown(f"**Region:** {st.session_state.get('region','Global') or 'Global'}")

    if slogan_text and slogan_text != "—":
        st.markdown(f"**Selected Tagline:** *\"{slogan_text}\"*")

    if isinstance(palette_obj, dict):
        st.markdown(f"**Palette:** {palette_obj.get('name','')} — {palette_obj.get('mood','')}")
        cols = st.columns(len(palette_obj.get("colors",[])))
        for col, hex_c in zip(cols, palette_obj.get("colors",[])):
            with col:
                st.markdown(
                    f'<div style="background:{hex_c};height:36px;border-radius:8px;'
                    f'margin-bottom:4px"></div><code style="font-size:0.7rem">{hex_c}</code>',
                    unsafe_allow_html=True,
                )

    if campaign:
        st.divider()
        st.subheader("Campaign Predictions (from trained ML models)")
        c1, c2, c3 = st.columns(3)
        c1.metric("CTR",        campaign.get("ctr","—"))
        c2.metric("ROI",        campaign.get("roi","—"))
        c3.metric("Engagement", campaign.get("engagement","—"))

    # ── Deployment checklist ──────────────────────────────────────────────────
    st.divider()
    st.subheader("Deployment Checklist (Week 10)")
    checklist = [
        ("CNN logo classifier trained (.h5) + embeddings (.npy)",          True),
        ("KNN font classifier serialised (.pkl) — font_knn.pkl",           True),
        ("KMeans colour extraction validated — colour_kmeans.pkl",         True),
        ("Gemini API slogan generation + NLTK preprocessing",              True),
        ("Matplotlib animation storyboard + GIF export",                   True),
        ("Random Forest campaign model (.pkl) with RMSE validation",       True),
        ("Multilingual Gemini API translation + BLEU score validation",    True),
        ("Feedback forms (logo/slogan/animation/campaign) + CSV logging",  True),
        ("Streamlit st.tabs() frontend with all 10 week modules",          True),
        ("Brand Kit ZIP download (logo, fonts, palette, slogans, campaign)",True),
        ("GitHub repository pushed with README + requirements.txt",        True),
        ("Streamlit Cloud deployment live",                                 True),
    ]
    for item, done in checklist:
        st.markdown(f"{'✅' if done else '○'} {item}")

    st.divider()

    with st.expander("📄 Full Integration Code (Week 10)"):
        st.code("""
# app.py — Week 10 Streamlit Cloud Deployment
import streamlit as st
import joblib
import numpy as np

st.set_page_config(page_title="BrandMind AI", page_icon="✦", layout="wide")

@st.cache_resource
def load_models():
    font_knn    = joblib.load('models/font_knn.pkl')
    font_le     = joblib.load('models/font_label_encoder.pkl')
    camp_ctr    = joblib.load('models/campaign_ctr_best.pkl')
    camp_roi    = joblib.load('models/campaign_roi_best.pkl')
    colour_km   = joblib.load('models/colour_kmeans.pkl')
    return font_knn, font_le, camp_ctr, camp_roi, colour_km

font_knn, font_le, camp_ctr, camp_roi, colour_km = load_models()

tabs = st.tabs(["Home","Logo & Font","Taglines","Animation",
                "Campaign","Multilingual","Feedback","Brand Kit","Chatbot"])
""", language="python")

    mark_done("W10")
